#!/usr/bin/env bash
#
# install.sh — one-line installer & lifecycle helper for Mayon.
#
#   curl -fsSL https://github.com/bendlikeabamboo/mayon/releases/latest/download/install.sh | bash
#
# It checks for Docker, generates a secure Postgres password, writes
# docker-compose.yml + .env into ~/.mayon, and starts the stack. Run
# ~/.mayon/install.sh <command> to manage it afterwards:
#   install | start | stop | restart | logs | status | upgrade | uninstall
#
# The version is baked in at release time (CI replaces the placeholder below).
set -euo pipefail

# --- Release version (CI sed-replaces the placeholder when attaching to a release) ---
MAYON_INSTALLER_VERSION="@MAYON_INSTALLER_VERSION@"
if [ "$MAYON_INSTALLER_VERSION" = "@MAYON_INSTALLER_VERSION@" ]; then
	MAYON_INSTALLER_VERSION="latest" # unbaked / dev checkout → track latest
fi

REPO="bendlikeabamboo/mayon"
INSTALL_DIR="${MAYON_DIR:-$HOME/.mayon}"
COMPOSE_FILE="$INSTALL_DIR/docker-compose.yml"
ENV_FILE="$INSTALL_DIR/.env"
INSTALLER_FILE="$INSTALL_DIR/install.sh"

if [ -t 1 ]; then
	C_BOLD=$'\033[1m'; C_CYAN=$'\033[36m'; C_GREEN=$'\033[32m'
	C_YELLOW=$'\033[33m'; C_RED=$'\033[31m'; C_RESET=$'\033[0m'
else
	C_BOLD=""; C_CYAN=""; C_GREEN=""; C_YELLOW=""; C_RED=""; C_RESET=""
fi

log() { printf '%s==>%s %s\n' "$C_BOLD$C_CYAN" "$C_RESET" "$*"; }
ok() { printf '%s✓%s %s\n' "$C_GREEN" "$C_RESET" "$*"; }
warn() { printf '%s!%s %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
die() { printf '%s✗%s %s\n' "$C_RED" "$C_RESET" "$*" >&2; exit 1; }

# Resolve the version to install: explicit override wins, else the baked one.
resolve_version() {
	echo "${MAYON_VERSION:-$MAYON_INSTALLER_VERSION}"
}

is_semver() {
	[[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
}

# URL of docker-compose.yml for a given version (tagged source on raw; main for latest).
compose_url_for() {
	local v="$1"
	if is_semver "$v"; then
		echo "https://raw.githubusercontent.com/${REPO}/v${v}/docker-compose.yml"
	else
		echo "https://raw.githubusercontent.com/${REPO}/main/docker-compose.yml"
	fi
}

# URL of this installer for a given version (release asset; /latest/ otherwise).
installer_url_for() {
	local v="$1"
	if is_semver "$v"; then
		echo "https://github.com/${REPO}/releases/download/v${v}/install.sh"
	else
		echo "https://github.com/${REPO}/releases/latest/download/install.sh"
	fi
}

download() { # download <url> <dest>
	local url="$1" dest="$2"
	if command -v curl >/dev/null 2>&1; then
		curl -fsSL "$url" -o "$dest"
	elif command -v wget >/dev/null 2>&1; then
		wget -qO "$dest" "$url"
	else
		die "Neither curl nor wget is installed. Install one and retry."
	fi
}

preflight() {
	command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/get-docker/"
	if ! docker compose version >/dev/null 2>&1; then
		die "The 'docker compose' plugin is missing. Update Docker Desktop / install the compose plugin."
	fi
}

gen_password() {
	if command -v openssl >/dev/null 2>&1; then
		openssl rand -hex 24
	else
		head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'
	fi
}

ensure_env() { # writes .env on first run, preserves it on upgrades
	if [ -f "$ENV_FILE" ]; then
		ok "Reusing existing config: $ENV_FILE"
		return
	fi
	local pass; pass="$(gen_password)" || die "Could not generate a password."
	{
		echo "# Mayon configuration — generated by install.sh"
		echo "POSTGRES_USER=mayon"
		echo "POSTGRES_DB=mayon"
		echo "POSTGRES_PASSWORD=${pass}"
		echo "# Web port (host). Change and restart to move off 8080."
		echo "MAYON_PORT=8080"
	} >"$ENV_FILE"
	chmod 600 "$ENV_FILE"
	ok "Generated config: $ENV_FILE"
}

# Pin the image tag into .env so upgrades stay on the chosen release unless changed.
ensure_version_pin() {
	local v; v="$(resolve_version)"
	if ! is_semver "$v"; then
		return # latest: let compose default to :latest, no pin
	fi
	if [ -f "$ENV_FILE" ] && grep -q '^MAYON_VERSION=' "$ENV_FILE"; then
		sed -i.bak -E "s|^MAYON_VERSION=.*|MAYON_VERSION=${v}|" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
	else
		echo "MAYON_VERSION=${v}" >>"$ENV_FILE"
	fi
}

save_self() { # keep a copy of the matching installer for later subcommands
	local v; v="$(resolve_version)"
	download "$(installer_url_for "$v")" "$INSTALLER_FILE"
	chmod +x "$INSTALLER_FILE"
}

compose_cmd() { (cd "$INSTALL_DIR" && docker compose "$@"); }

web_url() {
	local port="8080"
	if [ -f "$ENV_FILE" ] && grep -q '^MAYON_PORT=' "$ENV_FILE"; then
		port="$(sed -nE 's|^MAYON_PORT=([0-9]+).*|\1|p' "$ENV_FILE" | tail -n1)"
		[ -n "$port" ] || port="8080"
	fi
	echo "http://localhost:${port}"
}

cmd_install() {
	preflight
	mkdir -p "$INSTALL_DIR"
	local v; v="$(resolve_version)"
	log "Installing Mayon ${C_BOLD}${v}${C_RESET} into ${C_BOLD}${INSTALL_DIR}${C_RESET}"
	ensure_env
	ensure_version_pin
	log "Downloading docker-compose.yml…"
	download "$(compose_url_for "$v")" "$COMPOSE_FILE"
	save_self
	log "Pulling images…"
	compose_cmd pull
	log "Starting containers…"
	compose_cmd up -d
	echo
	ok "Mayon is up → $(web_url)"
	printf '  Manage with:  %s{stop,start,restart,logs,status,upgrade,uninstall}%s\n' "$C_BOLD" "$C_RESET"
	printf '  Directory:     %s\n' "$INSTALL_DIR"
	if is_semver "$v"; then
		printf '  Pinned to:     v%s (edit %s to change)\n' "$v" "$ENV_FILE"
	fi
}

cmd_start() { [ -f "$COMPOSE_FILE" ] || die "Not installed. Run: $(basename "$0") install"; compose_cmd up -d && ok "Started → $(web_url)"; }
cmd_stop() { [ -f "$COMPOSE_FILE" ] || die "Not installed."; compose_cmd stop && ok "Stopped."; }
cmd_restart() { [ -f "$COMPOSE_FILE" ] || die "Not installed."; compose_cmd restart && ok "Restarted → $(web_url)"; }
cmd_logs() { [ -f "$COMPOSE_FILE" ] || die "Not installed."; compose_cmd logs -f --tail=200; }
cmd_status() { [ -f "$COMPOSE_FILE" ] || die "Not installed."; compose_cmd ps; }

cmd_upgrade() {
	[ -f "$COMPOSE_FILE" ] || die "Not installed. Run install first."
	preflight
	log "Upgrading to the latest release…"
	# Fetch the latest (version-baked) installer and let its baked version pin the upgrade.
	local tmp; tmp="$(mktemp)"
	download "$(installer_url_for latest)" "$tmp"
	bash "$tmp" install
	rm -f "$tmp"
}

cmd_uninstall() {
	[ -f "$COMPOSE_FILE" ] || die "Not installed."
	warn "This stops and removes containers. Volumes (your data) are KEPT."
	read -r -p "Proceed? [y/N] " ans </dev/tty
	case "$ans" in
		y | Y | yes | YES) ;;
		*) die "Aborted." ;;
	esac
	compose_cmd down
	rm -f "$COMPOSE_FILE" "$ENV_FILE" "$INSTALLER_FILE"
	ok "Removed Mayon files. Data volumes remain in Docker (re-install to recover)."
}

usage() {
	cat <<EOF
Mayon installer — https://github.com/${REPO}

Usage (first run):   curl -fsSL <url>/install.sh | bash
       (afterwards): $(basename "$0") <command>

Commands:
  install     Install / re-deploy Mayon (default)
  start       Start a stopped stack
  stop        Stop the stack (keeps data)
  restart     Restart the stack
  logs        Follow container logs
  status      Show container status
  upgrade     Pull and deploy the latest release
  uninstall   Remove containers and files (keeps data volumes)

Environment:
  MAYON_VERSION   Pin a release (e.g. 0.1.0). Default: ${MAYON_INSTALLER_VERSION}
  MAYON_DIR       Install directory. Default: ~/.mayon
  MAYON_PORT      Web port (also writable in ~/.mayon/.env). Default: 8080
EOF
}

main() {
	local cmd="${1:-install}"
	case "$cmd" in
		-h | --help | help) usage ;;
		install) shift 2>/dev/null || true; cmd_install ;;
		start) cmd_start ;;
		stop | down) cmd_stop ;;
		restart) cmd_restart ;;
		logs) cmd_logs ;;
		status | ps) cmd_status ;;
		upgrade | update) cmd_upgrade ;;
		uninstall) cmd_uninstall ;;
		*) die "Unknown command '$cmd'. Run '$0 --help'." ;;
	esac
}

main "$@"
