<script lang="ts">
	import { onMount } from 'svelte';
	import { renderMarkdown } from '$lib/markdown/render';
	import { hasMermaid, renderMermaidBlock } from '$lib/markdown/mermaid';

	/**
	 * Renders sanitized markdown via `{@html}`. When the rendered HTML contains
	 * fenced mermaid blocks, each is lazily rendered to SVG and swapped in
	 * client-side after mount. Each message is its own component instance so
	 * Mermaid only loads for messages that actually need it.
	 */
	let { raw, class: className = '' }: { raw: string; class?: string } = $props();

	const html = $derived(renderMarkdown(raw));
	const needsMermaid = $derived(hasMermaid(html));

	let container = $state<HTMLDivElement | null>(null);

	onMount(() => {
		if (!needsMermaid || !container) return;
		// Mermaid is post-processed after the sanitized HTML is in the DOM. The
		// prose tree itself was sanitized; only SVG generated by mermaid is
		// injected here, on dedicated wrapper elements.
		const blocks = Array.from(container.querySelectorAll('code.language-mermaid'));
		for (const code of blocks) {
			const source = code.textContent ?? '';
			const pre = code.parentElement; // the <pre> wrapping the <code>
			void renderMermaidBlock(source)
				.then((svg) => {
					const wrapper = document.createElement('div');
					wrapper.className = 'mermaid-svg my-3 flex justify-center overflow-x-auto';
					wrapper.innerHTML = svg;
					pre?.replaceWith(wrapper);
				})
				.catch((err) => {
					const note = document.createElement('p');
					note.className = 'my-3 text-xs text-red-600 dark:text-red-400';
					note.textContent = `Mermaid render failed: ${err instanceof Error ? err.message : String(err)}`;
					pre?.replaceWith(note);
				});
		}
	});
</script>

<div bind:this={container} class="markdown-body {className}">
	<!-- eslint-disable-next-line svelte/no-at-html-tags -- sanitized by rehype-sanitize (allowlist in render.ts); mermaid SVG injected post-hoc on wrapper elements -->
	{@html html}
</div>

<style>
	:global(.markdown-body) {
		font-family: var(--font-serif);
		font-size: 0.875rem;
		line-height: 1.65;
		word-wrap: break-word;
	}
	:global(.markdown-body p) {
		margin: 0.5em 0;
	}
	:global(.markdown-body h1),
	:global(.markdown-body h2),
	:global(.markdown-body h3),
	:global(.markdown-body h4) {
		font-weight: 600;
		margin: 1em 0 0.4em;
		line-height: 1.3;
	}
	:global(.markdown-body h1) {
		font-size: 1.4em;
	}
	:global(.markdown-body h2) {
		font-size: 1.25em;
	}
	:global(.markdown-body h3) {
		font-size: 1.1em;
	}
	:global(.markdown-body ul),
	:global(.markdown-body ol) {
		margin: 0.5em 0;
		padding-left: 1.5em;
	}
	:global(.markdown-body li) {
		margin: 0.2em 0;
	}
	:global(.markdown-body a) {
		color: oklch(0.55 0.2 250);
		text-decoration: underline;
		text-underline-offset: 2px;
	}
	:global(.markdown-body blockquote) {
		border-left: 3px solid var(--border);
		padding-left: 1em;
		margin: 0.5em 0;
		color: var(--muted-foreground);
	}
	:global(.markdown-body :not(pre) > code) {
		background: var(--muted);
		padding: 0.15em 0.35em;
		border-radius: 0.25rem;
		font-size: 0.85em;
		font-family: ui-monospace, 'SF Mono', Menlo, monospace;
	}
	:global(.markdown-body pre) {
		background: var(--muted);
		padding: 0.75em 1em;
		border-radius: 0.5rem;
		overflow-x: auto;
		margin: 0.5em 0;
	}
	:global(.markdown-body pre code) {
		font-family: ui-monospace, 'SF Mono', Menlo, monospace;
		font-size: 0.825em;
		background: transparent;
		padding: 0;
	}
	:global(.markdown-body table) {
		border-collapse: collapse;
		width: 100%;
		margin: 0.5em 0;
		font-size: 0.85em;
	}
	:global(.markdown-body th),
	:global(.markdown-body td) {
		border: 1px solid var(--border);
		padding: 0.4em 0.6em;
		text-align: left;
	}
	:global(.markdown-body hr) {
		border: 0;
		border-top: 1px solid var(--border);
		margin: 1em 0;
	}
</style>
