<script lang="ts">
	import { onMount } from 'svelte';
	import XIcon from '@lucide/svelte/icons/x';
	import { RotateCcw } from '@lucide/svelte';
	import { computeCenter } from './mermaid-center';

	let {
		open,
		svgHtml,
		onClose
	}: {
		open: boolean;
		svgHtml: string;
		onClose: () => void;
	} = $props();

	type PanZoomInstance = {
		moveTo: (x: number, y: number) => void;
		zoomAbs: (x: number, y: number, zoom: number) => void;
		dispose: () => void;
	};

	let svgContainer = $state<HTMLDivElement | null>(null);
	let viewportPane = $state<HTMLDivElement | null>(null);
	let resetBtn = $state<HTMLButtonElement | null>(null);
	let pzInstance: PanZoomInstance | null = null;

	function close() {
		disposePanzoom();
		onClose();
	}

	function onOverlayClick(e: MouseEvent) {
		if (e.target === e.currentTarget) close();
	}

	function onKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			e.preventDefault();
			close();
		}
	}

	function disposePanzoom() {
		if (pzInstance) {
			pzInstance.dispose();
			pzInstance = null;
		}
	}

	function centerView(): boolean {
		if (!pzInstance || !svgContainer || !viewportPane) return false;
		const svgEl = svgContainer.firstElementChild as HTMLElement | null;
		if (!svgEl) return false;
		const svgBox = svgEl.getBoundingClientRect();
		if (svgBox.width === 0 || svgBox.height === 0) return false;
		const vpBox = viewportPane.getBoundingClientRect();
		const { x, y } = computeCenter(
			{ w: vpBox.width, h: vpBox.height },
			{ w: svgBox.width, h: svgBox.height }
		);
		pzInstance.moveTo(x, y);
		pzInstance.zoomAbs(x, y, 1);
		return true;
	}

	function resetPanZoom() {
		centerView();
	}

	onMount(() => {
		if (!svgContainer || !viewportPane) return;
		const container = svgContainer;
		import('panzoom').then((mod) => {
			const instance = mod.default(container, {
				minZoom: 0.5,
				maxZoom: 5,
				smoothScroll: false,
				filterKey: () => true
			});
			pzInstance = {
				moveTo: instance.moveTo.bind(instance),
				zoomAbs: instance.zoomAbs.bind(instance),
				dispose: instance.dispose.bind(instance)
			};
			resetBtn?.focus();

			let attempts = 0;
			const tryCenter = () => {
				if (centerView() || attempts++ > 30) return;
				requestAnimationFrame(tryCenter);
			};
			requestAnimationFrame(tryCenter);
		});

		let cleanup: (() => void) | undefined;
		if (typeof ResizeObserver !== 'undefined') {
			const ro = new ResizeObserver(() => {
				let retryAttempts = 0;
				const tryRecenter = () => {
					if (centerView() || retryAttempts++ > 30) return;
					requestAnimationFrame(tryRecenter);
				};
				requestAnimationFrame(tryRecenter);
			});
			ro.observe(viewportPane);
			cleanup = () => ro.disconnect();
		}
		return cleanup;
	});
</script>

<svelte:window onkeydown={onKeydown} onblur={close} />

{#if open}
	<div
		class="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
		onclick={onOverlayClick}
		onkeydown={onKeydown}
		role="dialog"
		tabindex="-1"
		aria-modal="true"
		aria-label="Mermaid diagram preview"
	>
		<div
			class="relative flex h-[90vh] w-[90vw] flex-col rounded-lg border border-border bg-card shadow-xl"
		>
			<div class="flex items-center justify-between border-b border-border px-4 py-2">
				<span class="text-sm font-medium text-foreground">Diagram Preview</span>
				<div class="flex items-center gap-1">
					<button
						bind:this={resetBtn}
						type="button"
						class="rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground"
						onclick={resetPanZoom}
						title="Reset pan/zoom"
					>
						<RotateCcw class="size-4" />
						<span class="sr-only">Reset</span>
					</button>
					<button
						type="button"
						class="rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground"
						onclick={close}
						title="Close"
					>
						<XIcon class="size-4" />
						<span class="sr-only">Close</span>
					</button>
				</div>
			</div>
			<div bind:this={viewportPane} class="flex-1 overflow-hidden">
				<div
					bind:this={svgContainer}
					class="flex h-full w-full items-center justify-center"
					style="max-width: none; max-height: none; width: auto; height: auto;"
				>
					<!-- eslint-disable-next-line svelte/no-at-html-tags -- SVG generated by mermaid, already sanitized -->
					{@html svgHtml}
				</div>
			</div>
		</div>
	</div>
{/if}
