<script lang="ts">
	import { onMount } from 'svelte';
	import XIcon from '@lucide/svelte/icons/x';
	import { RotateCcw } from '@lucide/svelte';

	let {
		open,
		svgHtml,
		onClose
	}: {
		open: boolean;
		svgHtml: string;
		onClose: () => void;
	} = $props();

	type PanZoomInstance = {
		moveTo: (x: number, y: number) => void;
		zoomAbs: (x: number, y: number, zoom: number) => void;
		dispose: () => void;
	};

	let svgContainer = $state<HTMLDivElement | null>(null);
	let resetBtn = $state<HTMLButtonElement | null>(null);
	let pzInstance: PanZoomInstance | null = null;

	function close() {
		disposePanzoom();
		onClose();
	}

	function onOverlayClick(e: MouseEvent) {
		if (e.target === e.currentTarget) close();
	}

	function onKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			e.preventDefault();
			close();
		}
	}

	function disposePanzoom() {
		if (pzInstance) {
			pzInstance.dispose();
			pzInstance = null;
		}
	}

	function resetPanZoom() {
		if (!pzInstance || !svgContainer) return;
		pzInstance.moveTo(0, 0);
		pzInstance.zoomAbs(0, 0, 1);
	}

	onMount(async () => {
		if (!svgContainer) return;
		const mod = await import('panzoom');
		const instance = mod.default(svgContainer, {
			minZoom: 0.5,
			maxZoom: 5,
			smoothScroll: false,
			filterKey: () => true
		});
		pzInstance = {
			moveTo: instance.moveTo.bind(instance),
			zoomAbs: instance.zoomAbs.bind(instance),
			dispose: instance.dispose.bind(instance)
		};
		resetBtn?.focus();
	});
</script>

<svelte:window onkeydown={onKeydown} onblur={close} />

{#if open}
	<div
		class="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
		onclick={onOverlayClick}
		onkeydown={onKeydown}
		role="dialog"
		tabindex="-1"
		aria-modal="true"
		aria-label="Mermaid diagram preview"
	>
		<div
			class="relative flex h-[90vh] w-[90vw] flex-col rounded-lg border border-border bg-card shadow-xl"
		>
			<div class="flex items-center justify-between border-b border-border px-4 py-2">
				<span class="text-sm font-medium text-foreground">Diagram Preview</span>
				<div class="flex items-center gap-1">
					<button
						bind:this={resetBtn}
						type="button"
						class="rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground"
						onclick={resetPanZoom}
						title="Reset pan/zoom"
					>
						<RotateCcw class="size-4" />
						<span class="sr-only">Reset</span>
					</button>
					<button
						type="button"
						class="rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground"
						onclick={close}
						title="Close"
					>
						<XIcon class="size-4" />
						<span class="sr-only">Close</span>
					</button>
				</div>
			</div>
			<div class="flex-1 overflow-hidden">
				<div
					bind:this={svgContainer}
					class="flex h-full w-full items-center justify-center"
					style="max-width: none; max-height: none; width: auto; height: auto;"
				>
					<!-- eslint-disable-next-line svelte/no-at-html-tags -- SVG generated by mermaid, already sanitized -->
					{@html svgHtml}
				</div>
			</div>
		</div>
	</div>
{/if}
