/**
 * Build-time script (run via `pnpm bundle:migrations` after `pnpm db:generate`).
 *
 * Reads `drizzle/meta/_journal.json` + every `<tag>.sql` and emits a static module
 * (`src/lib/db/driver/migrations.ts`) so the SPA can run migrations offline with no
 * runtime `node:fs` (which drizzle's built-in proxy migrator would require).
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const cwd = process.cwd();
const drizzleDir = resolve(cwd, 'drizzle');
const outPath = resolve(cwd, 'src/lib/db/driver/migrations.ts');

const journalPath = resolve(drizzleDir, 'meta/_journal.json');
if (!existsSync(journalPath)) {
	console.error(
		`[bundle-migrations] No meta/_journal.json in ${drizzleDir}. Run \`pnpm db:generate\` first.`
	);
	process.exit(1);
}

interface JournalEntry {
	idx: number;
	when: number;
	tag: string;
	breakpoints: boolean;
}

interface Journal {
	entries: JournalEntry[];
}

const journal = JSON.parse(readFileSync(journalPath, 'utf8')) as Journal;

const migrations = journal.entries.map((entry) => {
	const sqlPath = resolve(drizzleDir, `${entry.tag}.sql`);
	if (!existsSync(sqlPath)) {
		console.error(`[bundle-migrations] Missing migration file: ${sqlPath}`);
		process.exit(1);
	}
	const raw = readFileSync(sqlPath, 'utf8');
	const sql = raw
		.split('--> statement-breakpoint')
		.map((s) => s.trim())
		.filter(Boolean);
	const hash = createHash('sha256').update(raw).digest('hex');
	return { sql, folderMillis: entry.when, hash };
});

const body = JSON.stringify(migrations, null, '\t');

const file = `// AUTO-GENERATED by \`pnpm bundle:migrations\`. Do not edit by hand.
// Bundled drizzle migrations so the SPA can apply them offline (no runtime Node fs).
import type { MigrationMeta } from './types';

const migrations: MigrationMeta[] = ${body};

export default migrations;
`;

writeFileSync(outPath, file, 'utf8');
console.log(`[bundle-migrations] Wrote ${migrations.length} migration(s) -> ${outPath}`);
