// AUTO-GENERATED by `pnpm bundle:migrations`. Do not edit by hand.
// Bundled drizzle migrations so the SPA can apply them offline (no runtime Node fs).
import type { MigrationMeta } from './types';

const migrations: MigrationMeta[] = [
	{
		sql: [
			'CREATE TABLE `branch_sources` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`source_message_id` text NOT NULL,\n\t`start_char` integer NOT NULL,\n\t`end_char` integer NOT NULL,\n\t`excerpt` text NOT NULL,\n\t`branch_chat_id` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`source_message_id`) REFERENCES `messages`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`branch_chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `chats` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`parent_id` text,\n\t`root_id` text NOT NULL,\n\t`branch_point_message_id` text,\n\t`title` text NOT NULL,\n\t`depth` integer NOT NULL,\n\t`provider` text,\n\t`model` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`parent_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`root_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`branch_point_message_id`) REFERENCES `messages`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `cross_links` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`from_chat_id` text NOT NULL,\n\t`to_chat_id` text NOT NULL,\n\t`note` text,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`from_chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`to_chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action\n);',
			"CREATE TABLE `labs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`chat_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`content` text NOT NULL,\n\t`checklist` text DEFAULT '[]' NOT NULL,\n\t`model` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action\n);",
			'CREATE TABLE `messages` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`chat_id` text NOT NULL,\n\t`role` text NOT NULL,\n\t`content` text NOT NULL,\n\t`ord` integer NOT NULL,\n\t`model` text,\n\t`tokens` integer,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `quiz_answers` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`attempt_id` text NOT NULL,\n\t`question_id` text NOT NULL,\n\t`answer` text NOT NULL,\n\t`is_correct` integer,\n\t`ai_feedback` text,\n\t`graded_at` integer,\n\tFOREIGN KEY (`attempt_id`) REFERENCES `quiz_attempts`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`question_id`) REFERENCES `quiz_questions`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `quiz_attempts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`quiz_id` text NOT NULL,\n\t`score` integer,\n\t`started_at` integer NOT NULL,\n\t`finished_at` integer,\n\tFOREIGN KEY (`quiz_id`) REFERENCES `quizzes`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `quiz_questions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`quiz_id` text NOT NULL,\n\t`ord` integer NOT NULL,\n\t`type` text NOT NULL,\n\t`prompt` text NOT NULL,\n\t`payload` text NOT NULL,\n\tFOREIGN KEY (`quiz_id`) REFERENCES `quizzes`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `quizzes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`chat_id` text NOT NULL,\n\t`model` text,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `settings` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL\n);'
		],
		folderMillis: 1782370493595,
		hash: 'ece23599a9f422e27a8093673bf595103bdfb07332e6f11de8c7285583d487c5'
	},
	{
		sql: ['ALTER TABLE `chats` ADD `brief` text;'],
		folderMillis: 1782469750295,
		hash: '5861d0563f9d2aefdac2a48a81e5376ff1265a92128d4354832ce2f73600ed4e'
	},
	{
		sql: [
			'ALTER TABLE `messages` ADD `tool_call_id` text;',
			'ALTER TABLE `messages` ADD `tool_name` text;',
			'ALTER TABLE `messages` ADD `metadata` text;'
		],
		folderMillis: 1782665053149,
		hash: '9b63a08c69efb7f6b79ca332f7d7c30e7bececc43c8eaf68a42e970d119254b6'
	},
	{
		sql: [
			'CREATE TABLE `agent_traces` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`chat_id` text NOT NULL,\n\t`assistant_message_id` text,\n\t`model` text,\n\t`config_kind` text NOT NULL,\n\t`reasoning` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`duration_ms` integer,\n\t`trace` text NOT NULL,\n\tFOREIGN KEY (`chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`assistant_message_id`) REFERENCES `messages`(`id`) ON UPDATE no action ON DELETE no action\n);'
		],
		folderMillis: 1782748702546,
		hash: '10ed43a27aa8a958a2eaa2d1a0d973ec90d8db37d32a7b29718b61a45e2d2227'
	}
];

export default migrations;
