// AUTO-GENERATED by `pnpm bundle:migrations`. Do not edit by hand.
// Bundled drizzle migrations so the SPA can apply them offline (no runtime Node fs).
import type { MigrationMeta } from './types';

const migrations: MigrationMeta[] = [
	{
		sql: [
			'CREATE TABLE `branch_sources` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`source_message_id` text NOT NULL,\n\t`start_char` integer NOT NULL,\n\t`end_char` integer NOT NULL,\n\t`excerpt` text NOT NULL,\n\t`branch_chat_id` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`source_message_id`) REFERENCES `messages`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`branch_chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `chats` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`parent_id` text,\n\t`root_id` text NOT NULL,\n\t`branch_point_message_id` text,\n\t`title` text NOT NULL,\n\t`depth` integer NOT NULL,\n\t`provider` text,\n\t`model` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`parent_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`root_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`branch_point_message_id`) REFERENCES `messages`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `cross_links` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`from_chat_id` text NOT NULL,\n\t`to_chat_id` text NOT NULL,\n\t`note` text,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`from_chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`to_chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action\n);',
			"CREATE TABLE `labs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`chat_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`content` text NOT NULL,\n\t`checklist` text DEFAULT '[]' NOT NULL,\n\t`model` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action\n);",
			'CREATE TABLE `messages` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`chat_id` text NOT NULL,\n\t`role` text NOT NULL,\n\t`content` text NOT NULL,\n\t`ord` integer NOT NULL,\n\t`model` text,\n\t`tokens` integer,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `quiz_answers` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`attempt_id` text NOT NULL,\n\t`question_id` text NOT NULL,\n\t`answer` text NOT NULL,\n\t`is_correct` integer,\n\t`ai_feedback` text,\n\t`graded_at` integer,\n\tFOREIGN KEY (`attempt_id`) REFERENCES `quiz_attempts`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`question_id`) REFERENCES `quiz_questions`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `quiz_attempts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`quiz_id` text NOT NULL,\n\t`score` integer,\n\t`started_at` integer NOT NULL,\n\t`finished_at` integer,\n\tFOREIGN KEY (`quiz_id`) REFERENCES `quizzes`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `quiz_questions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`quiz_id` text NOT NULL,\n\t`ord` integer NOT NULL,\n\t`type` text NOT NULL,\n\t`prompt` text NOT NULL,\n\t`payload` text NOT NULL,\n\tFOREIGN KEY (`quiz_id`) REFERENCES `quizzes`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `quizzes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`chat_id` text NOT NULL,\n\t`model` text,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action\n);',
			'CREATE TABLE `settings` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL\n);'
		],
		folderMillis: 1782370493595,
		hash: 'ece23599a9f422e27a8093673bf595103bdfb07332e6f11de8c7285583d487c5'
	},
	{
		sql: ['ALTER TABLE `chats` ADD `brief` text;'],
		folderMillis: 1782469750295,
		hash: '5861d0563f9d2aefdac2a48a81e5376ff1265a92128d4354832ce2f73600ed4e'
	},
	{
		sql: [
			'ALTER TABLE `messages` ADD `tool_call_id` text;',
			'ALTER TABLE `messages` ADD `tool_name` text;',
			'ALTER TABLE `messages` ADD `metadata` text;'
		],
		folderMillis: 1782665053149,
		hash: '9b63a08c69efb7f6b79ca332f7d7c30e7bececc43c8eaf68a42e970d119254b6'
	},
	{
		sql: [
			'CREATE TABLE `agent_traces` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`chat_id` text NOT NULL,\n\t`assistant_message_id` text,\n\t`model` text,\n\t`config_kind` text NOT NULL,\n\t`reasoning` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`duration_ms` integer,\n\t`trace` text NOT NULL,\n\tFOREIGN KEY (`chat_id`) REFERENCES `chats`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`assistant_message_id`) REFERENCES `messages`(`id`) ON UPDATE no action ON DELETE no action\n);'
		],
		folderMillis: 1782748702546,
		hash: '10ed43a27aa8a958a2eaa2d1a0d973ec90d8db37d32a7b29718b61a45e2d2227'
	},
	{
		sql: [
			"ALTER TABLE `agent_traces` ADD `kind` text DEFAULT 'chat' NOT NULL;",
			'ALTER TABLE `agent_traces` ADD `lab_id` text REFERENCES labs(id);',
			'ALTER TABLE `agent_traces` ADD `quiz_id` text REFERENCES quizzes(id);'
		],
		folderMillis: 1782790610817,
		hash: '80d8f7980037295483bace262e043dd4b6186b1b95aaf014551b4bd66b42ea8a'
	},
	{
		sql: [
			'ALTER TABLE `branch_sources` ADD `custom_instructions` text;',
			'ALTER TABLE `branch_sources` ADD `add_formats` text;'
		],
		folderMillis: 1783008654126,
		hash: 'e55cb1f5138b70eaf4fdad4922e8cf580af7c0975db22121ebaa0b1262b6e932'
	},
	{
		sql: [
			"-- FTS5 full-text search index (hand-authored, NOT a drizzle model).\n-- Kept in sync by triggers on messages, chats, labs, quiz_questions.\n-- Do NOT add to schema.ts — FTS5 virtual tables are not drizzle tables.\nCREATE VIRTUAL TABLE search_fts USING fts5(\n  kind UNINDEXED,\n  title,\n  body,\n  chat_id UNINDEXED,\n  ref_id UNINDEXED,\n  quiz_id UNINDEXED,\n  tokenize = 'unicode61 remove_diacritics 2'\n);",
			"-- messages\nCREATE TRIGGER search_fts_messages_ai AFTER INSERT ON messages BEGIN\n  INSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n    VALUES('message','',new.content,new.chat_id,new.id,NULL);\nEND;",
			"CREATE TRIGGER search_fts_messages_ad AFTER DELETE ON messages BEGIN\n  DELETE FROM search_fts WHERE kind='message' AND ref_id = old.id;\nEND;",
			"CREATE TRIGGER search_fts_messages_au AFTER UPDATE ON messages BEGIN\n  DELETE FROM search_fts WHERE kind='message' AND ref_id = old.id;\n  INSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n    VALUES('message','',new.content,new.chat_id,new.id,NULL);\nEND;",
			"-- chats (title only)\nCREATE TRIGGER search_fts_chats_ai AFTER INSERT ON chats BEGIN\n  INSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n    VALUES('chat',new.title,'',new.id,new.id,NULL);\nEND;",
			"CREATE TRIGGER search_fts_chats_ad AFTER DELETE ON chats BEGIN\n  DELETE FROM search_fts WHERE kind='chat' AND ref_id = old.id;\nEND;",
			"CREATE TRIGGER search_fts_chats_au AFTER UPDATE ON chats BEGIN\n  DELETE FROM search_fts WHERE kind='chat' AND ref_id = old.id;\n  INSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n    VALUES('chat',new.title,'',new.id,new.id,NULL);\nEND;",
			"-- labs (title + content)\nCREATE TRIGGER search_fts_labs_ai AFTER INSERT ON labs BEGIN\n  INSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n    VALUES('lab',new.title,new.content,new.chat_id,new.id,NULL);\nEND;",
			"CREATE TRIGGER search_fts_labs_ad AFTER DELETE ON labs BEGIN\n  DELETE FROM search_fts WHERE kind='lab' AND ref_id = old.id;\nEND;",
			"CREATE TRIGGER search_fts_labs_au AFTER UPDATE ON labs BEGIN\n  DELETE FROM search_fts WHERE kind='lab' AND ref_id = old.id;\n  INSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n    VALUES('lab',new.title,new.content,new.chat_id,new.id,NULL);\nEND;",
			"-- quiz_questions (prompt; chat_id resolved via the quiz)\nCREATE TRIGGER search_fts_qq_ai AFTER INSERT ON quiz_questions BEGIN\n  INSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n    SELECT 'quiz_question','',new.prompt,q.chat_id,new.id,new.quiz_id\n    FROM quizzes q WHERE q.id = new.quiz_id;\nEND;",
			"CREATE TRIGGER search_fts_qq_ad AFTER DELETE ON quiz_questions BEGIN\n  DELETE FROM search_fts WHERE kind='quiz_question' AND ref_id = old.id;\nEND;",
			"CREATE TRIGGER search_fts_qq_au AFTER UPDATE ON quiz_questions BEGIN\n  DELETE FROM search_fts WHERE kind='quiz_question' AND ref_id = old.id;\n  INSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n    SELECT 'quiz_question','',new.prompt,q.chat_id,new.id,new.quiz_id\n    FROM quizzes q WHERE q.id = new.quiz_id;\nEND;",
			"-- one-time backfill (raw text — noise stripping is applied only by rebuildIndex())\nINSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n  SELECT 'chat', title, '', id, id, NULL FROM chats;",
			"INSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n  SELECT 'message', '', content, chat_id, id, NULL FROM messages;",
			"INSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n  SELECT 'lab', title, content, chat_id, id, NULL FROM labs;",
			"INSERT INTO search_fts(kind,title,body,chat_id,ref_id,quiz_id)\n  SELECT 'quiz_question', '', qq.prompt, q.chat_id, qq.id, qq.quiz_id\n  FROM quiz_questions qq JOIN quizzes q ON q.id = qq.quiz_id;"
		],
		folderMillis: 1783164800000,
		hash: '6042942feb9e6abbe4cfa57be4c4f57757aa3ec02881f1603f248f5a28f3ded0'
	},
	{
		sql: ['ALTER TABLE `chats` ADD `mcp_config` text;'],
		folderMillis: 1783418066260,
		hash: '2aca6730b865b3512ce519585a1aa19c2de1c9e695533bea92b6296bbdb739f1'
	}
];

export default migrations;
